
import Head from 'next/head'
import { Box } from '@mui/material';

import ContactInfo from '../components/ContactInfo'
import NavBar from '../components/NavBar';
import Footer from '../components/Footer';

export default function Contact() {
    return (
        <Box>
            <Head>
                <title>My Contact:</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar></NavBar>
            <ContactInfo />
            <footer className='[styles.footer]'></footer>
            <Footer className='[styles.footer]'></Footer>
        </Box>
    )
}